#version 430 core

layout(local_size_x = 128) in;

layout(std430, binding = 0) buffer CurrentPositions {
    float current_positions[];
};

layout(std430, binding = 1) buffer PreviousPositions {
    float previous_positions[];
};

uniform uint uVertexCount;
uniform vec3 uAccelerationDisplacement;

void main()
{
    uint vertex_index = gl_GlobalInvocationID.x;
    if (vertex_index >= uVertexCount) {
        return;
    }

    uint position_base = vertex_index * 3u;
    vec3 current = vec3(current_positions[position_base],
                        current_positions[position_base + 1u],
                        current_positions[position_base + 2u]);
    vec3 previous = vec3(previous_positions[position_base],
                        previous_positions[position_base + 1u],
                        previous_positions[position_base + 2u]);

    // delta_s = v * dt + a * dt^2 = (current - previous) + uAccelerationDisplacement
    vec3 next = current +
                (current - previous) +
                uAccelerationDisplacement;

    previous_positions[position_base] = current.x;
    previous_positions[position_base + 1u] = current.y;
    previous_positions[position_base + 2u] = current.z;

    current_positions[position_base] = next.x;
    current_positions[position_base + 1u] = next.y;
    current_positions[position_base + 2u] = next.z;
}
