#ifndef SIMULATION_BUFFER_BINDINGS_GLSL
#define SIMULATION_BUFFER_BINDINGS_GLSL

// Cloth range: 0..18
#define CLOTH_CURRENT_POSITIONS 0
#define CLOTH_PREVIOUS_POSITIONS 1
#define CLOTH_COLLISION_PUSHOUTS 2
#define CLOTH_CLOTH_PUSHOUTS 3
#define CLOTH_CONTACT_MOTION_DELTAS 4
#define CLOTH_TRIANGLE_VERTEX_INDICES 6
#define CLOTH_ADJACENT_TRIANGLE_OFFSETS 7
#define CLOTH_ADJACENT_TRIANGLE_INDICES 8
#define STRETCH_EDGE_INDICES 9
#define STRETCH_REST_LENGTHS 10
#define BENDING_EDGE_INDICES 11
#define BENDING_REST_LENGTHS 12
#define ATTACHMENT_INDICES 13
#define ATTACHMENT_BARYCENTRIC_OFFSETS 14
#define CLOTH_TRIANGLE_NORMALS 15
#define CLOTH_VERTEX_NORMALS 16
#define CLOTH_BVH_NODES 17
#define CLOTH_TRIANGLE_BOUNDS 18

// Character range: 19..35
#define CHARACTER_ALL_FRAME_POSITIONS 19
#define CHARACTER_PREVIOUS_POSITIONS 20
#define CHARACTER_CURRENT_POSITIONS 21
#define CHARACTER_TRIANGLE_INDICES 22
#define BODY_TRIANGLE_BVH_NODES 23
#define BODY_TRIANGLE_BOUNDS 24
#define BODY_VERTEX_BVH_NODES 25
#define BODY_BVH_VERTEX_INDICES 26
#define BODY_VERTEX_BOUNDS 27
#define BODY_EDGE_BVH_NODES 28
#define BODY_EDGE_INDICES 29
#define BODY_EDGE_BOUNDS 30
#define CHARACTER_ADJACENT_TRIANGLE_OFFSETS 31
#define CHARACTER_ADJACENT_TRIANGLE_INDICES 32
#define BODY_TRIANGLE_POSITIONS 33
#define BODY_TRIANGLE_NORMALS 34
#define CHARACTER_VERTEX_NORMALS 35

// Collision range: 36..50
#define CLOTH_VERTEX_BODY_FACE_CANDIDATES 36
#define CLOTH_VERTEX_BODY_FACE_CANDIDATE_COUNT 37
#define CLOTH_VERTEX_BODY_FACE_DISPATCH_SIZE 38
#define CLOTH_EDGE_BODY_EDGE_CANDIDATES 39
#define CLOTH_EDGE_BODY_EDGE_CANDIDATE_COUNT 40
#define CLOTH_EDGE_BODY_EDGE_DISPATCH_SIZE 41
#define CLOTH_FACE_BODY_VERTEX_CANDIDATES 42
#define CLOTH_FACE_BODY_VERTEX_CANDIDATE_COUNT 43
#define CLOTH_FACE_BODY_VERTEX_DISPATCH_SIZE 44
#define CLOTH_CLOTH_VERTEX_FACE_CANDIDATES 45
#define CLOTH_CLOTH_VERTEX_FACE_CANDIDATE_COUNT 46
#define CLOTH_CLOTH_VERTEX_FACE_DISPATCH_SIZE 47
#define NORMAL_CORRECTION_SUMS 48
#define FRICTION_CORRECTION_SUMS 49
#define CONTACT_MOTION_DELTA_SUMS 50

#define CLOTH_VERTEX_FACE_EXCLUSIONS 57

#endif
