#ifndef SIMULATION_BUFFER_BINDINGS_GLSL
#define SIMULATION_BUFFER_BINDINGS_GLSL

// Cloth range: 0..20
#define CLOTH_CURRENT_POSITIONS 0
#define CLOTH_PREVIOUS_POSITIONS 1
#define CLOTH_COLLISION_PUSHOUTS 2
#define CLOTH_INWARD_MOTION_CORRECTIONS 3
#define CLOTH_EDGE_EXCLUSIONS 4
#define CLOTH_TRIANGLE_VERTEX_INDICES 5
#define CLOTH_ADJACENT_TRIANGLE_OFFSETS 6
#define CLOTH_ADJACENT_TRIANGLE_INDICES 7
#define STRETCH_EDGE_INDICES 8
#define STRETCH_REST_LENGTHS 9
#define BENDING_EDGE_INDICES 10
#define BENDING_REST_LENGTHS 11
#define ATTACHMENT_INDICES 12
#define ATTACHMENT_BARYCENTRIC_OFFSETS 13
#define CLOTH_TRIANGLE_NORMALS 14
#define CLOTH_VERTEX_NORMALS 15
#define CLOTH_BVH_NODES 16
#define CLOTH_TRIANGLE_BOUNDS 17
#define CLOTH_EDGE_INDICES 18
#define CLOTH_EDGE_BOUNDS 19
#define CLOTH_EDGE_BVH_NODES 20

// Character range: 21..34
#define CHARACTER_ALL_FRAME_POSITIONS 21
#define CHARACTER_PREVIOUS_POSITIONS 22
#define CHARACTER_CURRENT_POSITIONS 23
#define CHARACTER_TRIANGLE_INDICES 24
#define BODY_TRIANGLE_BVH_NODES 25
#define BODY_TRIANGLE_BOUNDS 26
#define BODY_EDGE_BVH_NODES 27
#define BODY_EDGE_INDICES 28
#define BODY_EDGE_BOUNDS 29
#define CHARACTER_ADJACENT_TRIANGLE_OFFSETS 30
#define CHARACTER_ADJACENT_TRIANGLE_INDICES 31
#define BODY_TRIANGLE_POSITIONS 32
#define BODY_TRIANGLE_NORMALS 33
#define CHARACTER_VERTEX_NORMALS 34

// Collision range: 35..49
#define CLOTH_VERTEX_BODY_FACE_CANDIDATES 35
#define CLOTH_VERTEX_BODY_FACE_CANDIDATE_COUNT 36
#define CLOTH_VERTEX_BODY_FACE_DISPATCH_SIZE 37
#define CLOTH_EDGE_BODY_EDGE_CANDIDATES 38
#define CLOTH_EDGE_BODY_EDGE_CANDIDATE_COUNT 39
#define CLOTH_EDGE_BODY_EDGE_DISPATCH_SIZE 40
#define CLOTH_CLOTH_VERTEX_FACE_CANDIDATES 41
#define CLOTH_CLOTH_VERTEX_FACE_CANDIDATE_COUNT 42
#define CLOTH_CLOTH_VERTEX_FACE_DISPATCH_SIZE 43
#define NORMAL_CORRECTION_SUMS 44
#define FRICTION_CORRECTION_SUMS 45
#define INWARD_MOTION_CORRECTION_SUMS 46

#define CLOTH_CLOTH_EDGE_EDGE_CANDIDATES 47
#define CLOTH_CLOTH_EDGE_EDGE_CANDIDATE_COUNT 48
#define CLOTH_CLOTH_EDGE_EDGE_DISPATCH_SIZE 49

#define CLOTH_VERTEX_FACE_EXCLUSIONS 57

#endif
