#version 430 core

#include "../simulation_buffer_bindings.glsl"

layout(local_size_x = 128) in;

layout(std430, binding = CLOTH_CURRENT_POSITIONS) buffer CurrentPositions {
    vec4 current_positions[];
};

layout(std430, binding = CLOTH_PREVIOUS_POSITIONS) buffer PreviousPositions {
    vec4 previous_positions[];
};

layout(std430, binding = CLOTH_COLLISION_PUSHOUTS) buffer CollisionPushouts {
    vec4 collision_pushouts[];
};

layout(std430, binding = CLOTH_CLOTH_PUSHOUTS) buffer ClothClothPushouts {
    vec4 cloth_cloth_pushouts[];
};

layout(std430, binding = CLOTH_CONTACT_MOTION_DELTAS) buffer ContactMotionDeltas {
    vec4 contact_motion_deltas[];
};

uniform uint uVertexOffset;
uniform uint uVertexCount;

uniform mat3 uDisplacementCoefficient;
uniform mat3 uPositionCoefficient;
uniform vec3 uPositionOffset;

void main()
{
    uint garment_vertex_index = gl_GlobalInvocationID.x;
    if (garment_vertex_index >= uVertexCount) {
        return;
    }
    uint vertex_index = uVertexOffset + garment_vertex_index;

    vec3 current = current_positions[vertex_index].xyz;
    vec3 previous = previous_positions[vertex_index].xyz;

    // update pos
    vec3 collision_pushout = collision_pushouts[vertex_index].xyz;
    vec3 cloth_cloth_pushout = cloth_cloth_pushouts[vertex_index].xyz;
    vec3 position_delta = current - previous - collision_pushout - cloth_cloth_pushout + contact_motion_deltas[vertex_index].xyz;
    vec3 next = uPositionCoefficient * current + uDisplacementCoefficient * position_delta + uPositionOffset;

    previous_positions[vertex_index] = vec4(current, 0.0);
    current_positions[vertex_index] = vec4(next, 0.0);

    // reset
    collision_pushouts[vertex_index] = vec4(0.0);
    cloth_cloth_pushouts[vertex_index] = vec4(0.0);
    contact_motion_deltas[vertex_index] = vec4(0.0);
}
