#version 430 core

layout(local_size_x = 128) in;

#include "primitive_geometry.glsl"

layout(std430, binding = 0) readonly buffer Positions {
    vec4 positions[];
};

layout(std430, binding = 1) readonly buffer Indices {
    uint indices[];
};

layout(std430, binding = 2) writeonly buffer TriangleNormals {
    vec4 triangle_normals[];
};

uniform uint uTriangleCount;

void main()
{
    uint triangle_index = gl_GlobalInvocationID.x;
    if (triangle_index >= uTriangleCount) {
        return;
    }

    uint index_base = triangle_index * 3u;
    uint i0 = indices[index_base];
    uint i1 = indices[index_base + 1u];
    uint i2 = indices[index_base + 2u];

    vec3 p0 = positions[i0].xyz;
    vec3 p1 = positions[i1].xyz;
    vec3 p2 = positions[i2].xyz;

    triangle_normals[triangle_index] = triangle_normal(p0, p1, p2);
}
