#version 430 core

layout(local_size_x = 128) in;

struct CharacterTriangleGeometry {
    vec4 a;
    vec4 b;
    vec4 c;
    vec4 normal;
};

struct MeshBvhNode {
    vec4 min_bounds;
    vec4 max_bounds;
    uint left_child_index;
    uint right_child_index;
    uint first_triangle_index;
    uint triangle_count;
};

bool is_leaf_node(MeshBvhNode node)
{
    return node.triangle_count > 0u;
}

layout(std430, binding = 0) readonly buffer CharacterTriangleGeometryBuffer {
    CharacterTriangleGeometry triangle_geometry[];
};

layout(std430, binding = 1) buffer MeshBvhNodeBuffer {
    MeshBvhNode bvh_nodes[];
};

uniform uint uFirstNode;
uniform uint uNodeCount;

void update_leaf_bounds(uint node_index, MeshBvhNode node)
{
    vec3 min_bounds = vec3(3.402823e+38);
    vec3 max_bounds = vec3(-3.402823e+38);
    for (uint triangle_offset = 0u; triangle_offset < node.triangle_count; ++triangle_offset) {
        uint triangle_index = node.first_triangle_index + triangle_offset;
        vec3 a = triangle_geometry[triangle_index].a.xyz;
        vec3 b = triangle_geometry[triangle_index].b.xyz;
        vec3 c = triangle_geometry[triangle_index].c.xyz;
        min_bounds = min(min_bounds, min(a, min(b, c)));
        max_bounds = max(max_bounds, max(a, max(b, c)));
    }

    bvh_nodes[node_index].min_bounds = vec4(min_bounds, 0.0);
    bvh_nodes[node_index].max_bounds = vec4(max_bounds, 0.0);
}

void update_internal_bounds(uint node_index, MeshBvhNode node)
{
    vec3 min_bounds = min(bvh_nodes[node.left_child_index].min_bounds.xyz, bvh_nodes[node.right_child_index].min_bounds.xyz);
    vec3 max_bounds = max(bvh_nodes[node.left_child_index].max_bounds.xyz, bvh_nodes[node.right_child_index].max_bounds.xyz);

    bvh_nodes[node_index].min_bounds = vec4(min_bounds, 0.0);
    bvh_nodes[node_index].max_bounds = vec4(max_bounds, 0.0);
}

void main()
{
    uint local_node_index = gl_GlobalInvocationID.x;
    if (local_node_index >= uNodeCount) {
        return;
    }

    uint node_index = uFirstNode + local_node_index;
    MeshBvhNode node = bvh_nodes[node_index];
    if (is_leaf_node(node)) {
        update_leaf_bounds(node_index, node);
    } else {
        update_internal_bounds(node_index, node);
    }
}
